<?php

return [
    // Fuentes en español
    'peruNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=peru',
        'language' => 'es',
        'source' => 'Perú',
        'country' => 'Perú',
    ],
    'boliviaNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=bolivia',
        'language' => 'es',
        'source' => 'Bolivia',
        'country' => 'Bolivia',
    ],
    'argentinaNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=argentina',
        'language' => 'es',
        'source' => 'Argentina',
        'country' => 'Argentina',
    ],
    'chileNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=chile',
        'language' => 'es',
        'source' => 'Chile',
        'country' => 'Chile',
    ],
    'colombiaNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=colombia',
        'language' => 'es',
        'source' => 'Colombia',
        'country' => 'Colombia',
    ],
    'costaRicaNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=costa-rica',
        'language' => 'es',
        'source' => 'Costa Rica',
        'country' => 'Costa Rica',
    ],
    'ecuadorNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=ecuador',
        'language' => 'es',
        'source' => 'Ecuador',
        'country' => 'Ecuador',
    ],
    'elSalvadorNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=el-salvador',
        'language' => 'es',
        'source' => 'El Salvador',
        'country' => 'El Salvador',
    ],
    'españaNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=spain',
        'language' => 'es',
        'source' => 'España',
        'country' => 'España',
    ],
    'guatemalaNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=guatemala',
        'language' => 'es',
        'source' => 'Guatemala',
        'country' => 'Guatemala',
    ],
    'hondurasNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=honduras',
        'language' => 'es',
        'source' => 'Honduras',
        'country' => 'Honduras',
    ],
    'mexicoNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=mexico',
        'language' => 'es',
        'source' => 'México',
        'country' => 'México',
    ],
    'nicaraguaNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=nicaragua',
        'language' => 'es',
        'source' => 'Nicaragua',   
        'country' => 'Nicaragua',
    ],
    'panamaNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=panamá',
        'language' => 'es',
        'source' => 'Panamá',
        'country' => 'Panamá',
    ],
    'paraguayNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=paraguay',
        'language' => 'es',
        'source' => 'Paraguay',
        'country' => 'Paraguay',
    ],
    'puertoRicoNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=puerto-rico',
        'language' => 'es',
        'source' => 'Puerto Rico',
        'country' => 'Puerto Rico',
    ],
    'republicaDominicanaNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=dominican-republic',
        'language' => 'es',
        'source' => 'República Dominicana',
        'country' => 'República Dominicana',
    ],
    'uruguayNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=uruguay',
        'language' => 'es',
        'source' => 'Uruguay',
        'country' => 'Uruguay',
    ],
    'usaEspañolNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=spanish',
        'language' => 'es',
        'source' => 'USA (Español)',
        'country' => 'Estados Unidos',
    ],
    'venezuelaNews' => [
        'url' => 'https://noticias.laiglesiadejesucristo.org/rss?country=venezuela',
        'language' => 'es',
        'source' => 'Venezuela',
        'country' => 'Venezuela',
    ],

    // Fuentes en inglés
    'africaNews' => [
        'url' => 'https://news-africa.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Africa',
        'country' => 'Africa',
    ],
    'australiaNews' => [
        'url' => 'https://news-au.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Australia',
        'country' => 'Australia',
    ],
    'barbadosNews' => [
        'url' => 'https://news-bb.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Barbados',
        'country' => 'Barbados',
    ],
    'belizeNews' => [
        'url' => 'https://news-bz.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Belize',
        'country' => 'Belize',
    ],
    'cambodiaNews' => [
        'url' => 'https://news-kh.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Camboya',
        'country' => 'Camboya',
    ],
    'canadaNews' => [
        'url' => 'https://news-ca.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Canadá',
        'country' => 'Canadá',
    ],
    'europaNews' => [
        'url' => 'https://news-europe.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Europa',
        'country' => 'Europa',
    ],
    'filipinasNews' => [
        'url' => 'https://news-ph.churchofjesuschrist.org/rss?country=philippines',
        'language' => 'en',
        'source' => 'Filipinas',
        'country' => 'Filipinas',
    ],
    'ghanaNews' => [
        'url' => 'https://news-gh.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Ghana',
        'country' => 'Ghana',
    ],
    'hongKongNews' => [
        'url' => 'https://news-hk.churchofjesuschrist.org/eng/rss',
        'language' => 'en',
        'source' => 'Hong Kong',
        'country' => 'China',
    ],
    'indiaNews' => [
        'url' => 'https://news-in.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'India',
        'country' => 'India',
    ],
    'irlandaNews' => [
        'url' => 'https://news-europe.churchofjesuschrist.org/rss?country=ireland',
        'language' => 'en',
        'source' => 'Irlanda',
        'country' => 'Irlanda',
    ],
    'middleEastNews' => [
        'url' => 'https://news-middleeast.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Medio Oriente',
        'country' => 'Medio Oriente',
    ],
    'micronesiaNews' => [
        'url' => 'https://news-gu.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Micronesia',
        'country' => 'Micronesia',
    ],
    'newZealandNews' => [
        'url' => 'https://news-nz.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Nueva Zelanda',
        'country' => 'Nueva Zelanda',
    ],
    'nigeriaNews' => [
        'url' => 'https://news-ng.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Nigeria',
        'country' => 'Nigeria',
    ],
    'pacificNews' => [
        'url' => 'https://news-pacific.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Pacífico',
        'country' => 'Pacífico',
    ],
    'papuaNewGuineaNews' => [
        'url' => 'https://news-pg.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Papúa Nueva Guinea',
        'country' => 'Papúa Nueva Guinea',
    ],
    'reinoUnidoNews' => [
        'url' => 'https://news-uk.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Reino Unido',
        'country' => 'Reino Unido',
    ],
    'sierraLeoneNews' => [
        'url' => 'https://news-sl.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Sierra Leona',
        'country' => 'Sierra Leona',
    ],
    'singaporeNews' => [
        'url' => 'https://news-sg.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Singapur',
        'country' => 'Singapur',
    ],
    'southAfricaNews' => [
        'url' => 'https://news-za.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Sudáfrica',
        'country' => 'Sudáfrica',
    ],
    'ugandaNews' => [
        'url' => 'https://news-ug.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Uganda',
        'country' => 'Uganda',
    ],
    'usaMainNews' => [
        'url' => 'https://newsroom.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'USA Main News',
        'country' => 'Estados Unidos',
    ],
    'usaMemberNews' => [
        'url' => 'https://newsroom.churchofjesuschrist.org/member-news/rss',
        'language' => 'en',
        'source' => 'USA Member News',
        'country' => 'Estados Unidos',
    ],
    'usaNewsReleases' => [
        'url' => 'https://newsroom.churchofjesuschrist.org/news-releases/rss',
        'language' => 'en',
        'source' => 'USA News Releases',
        'country' => 'Estados Unidos',
    ],
    'zimbabweNews' => [
        'url' => 'https://news-zw.churchofjesuschrist.org/rss',
        'language' => 'en',
        'source' => 'Zimbabwe',
        'country' => 'Zimbabwe',
    ],

    // Fuentes en portugués
    'angolaNews' => [
        'url' => 'https://noticias-ao.aigrejadejesuscristo.org/rss',
        'language' => 'pt',
        'source' => 'Angola',
        'country' => 'Angola',
    ],
    'brasilNews' => [
        'url' => 'https://noticias-br.aigrejadejesuscristo.org/rss',
        'language' => 'pt',
        'source' => 'Brasil',
        'country' => 'Brasil',
    ],
    'caboVerdeaNews' => [
        'url' => 'https://noticias-br.aigrejadejesuscristo.org/rss',
        'language' => 'pt',
        'source' => 'Cabo Verde',
        'country' => 'Cabo Verde',
    ],
    'mozambiqueNews' => [
        'url' => 'https://noticias-mz.aigrejadejesuscristo.org/rss',
        'language' => 'pt',
        'source' => 'Mozambique',
        'country' => 'Mozambique',
    ],

    // Fuentes en francés
    'belgicaNews' => [
        'url' => 'https://presse-be.eglisedejesus-christ.org/rss',
        'language' => 'fr',
        'source' => 'Bélgica',
        'country' => 'Bélgica',
    ],
    'costaDeMarfilNews' => [
        'url' => 'https://presse-ci.eglisedejesus-christ.org/rss',
        'language' => 'fr',
        'source' => 'Costa de Marfil',
        'country' => 'Costa de Marfil',
    ],
    'franciaNews' => [
        'url' => 'https://presse-fr.eglisedejesus-christ.org/rss',
        'language' => 'fr',
        'source' => 'Francia',
        'country' => 'Francia',
    ],
];
